#spring:
#  application:
#    name: Order-Service
#  datasource:
#    url: jdbc:h2:mem:order
#    username: root
#    password: root
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.H2Dialect
#
#server:
#  port: 8300


spring:
  application:
    name: Book-Service
  datasource:
    url: jdbc:h2:mem:ordering
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8400